USE CampusRestaurant;
GO
IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='FOOD') DROP TABLE FOOD;
IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='Restaurants') DROP TABLE Restaurants;
IF EXISTS(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME='Users') DROP TABLE Users;
GO

CREATE TABLE Restaurants(
	RES_ID INT NOT NULL IDENTITY(1,1),
	RES_NAME VARCHAR(100) UNIQUE,
	RES_ADDRESS VARCHAR(100),
	RES_HOURS VARCHAR(50),
	RES_DAYS VARCHAR (50),
	RES_PHONENO VARCHAR(15),
	RES_LOGO VARCHAR (1000),
	PRIMARY KEY(RES_ID)
);

CREATE TABLE FOOD(
	FOOD_ID INT NOT NULL IDENTITY(1,1),
	FOOD_NAME VARCHAR(1000),
	FOOD_PRICE FLOAT,
	FOOD_DESC VARCHAR(1000),
	IMG_SRC VARCHAR(1000),
	RES_ID INT,
	FOREIGN KEY (RES_ID) REFERENCES Restaurants(RES_ID),
	PRIMARY KEY (FOOD_ID)
);

CREATE TABLE Users(
	User_ID INT NOT NULL IDENTITY(1,1),
	User_FNAME VARCHAR(1000),
    User_LNAME VARCHAR(1000),
	User_TYPE VARCHAR(1000),
	User_PHONE VARCHAR(1000),
	User_EMAIL VARCHAR (1000) UNIQUE,
	User_PASSWORD VARCHAR (1000),
	User_LOCATION VARCHAR (1000),
	PRIMARY KEY(User_ID)
);

USE master;

